name: Publish Python 🐍 distribution 📦 to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  build-and-publish:
    permissions:
      id-token: write  # Required for trusted publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # No username/password needed for trusted publishing!
          # PyPI will authenticate using OIDC
          # repository-url: https://test.pypi.org/legacy/  # Uncomment for TestPyPI
